### ISSUE TITLE
[Bug] [MultiPlayer] Immersive Engineering - Core Sample Drill

### ISSUE THREAD

**Issue by RoslynMC** [AllTheMods/ATM-1#38] opened 2017-05-26 21:08 UTC
Unable to extract core sample from drill with right click/anything that can extract items whilst in a multi-player server. This however works perfectly fine in single player. Server file config has same settings for this as single player. Still does not work in multi-player.

**Comment by Marker248** [comment] 2017-05-29 03:56
I have noticed this also. I'm not sure if it coincides with the immersive petroleum add-on as i haven't used the core sample drill until after this update.
Still it makes little sense that it works perfectly fine in single player
I might try to install the server pack that doesn't have immersive petroleum and see if it works or not.

**Comment by Marker248** [comment] 2017-06-08 05:28
I updated Immersive petroleum to version 1.04 and the issue is no longer there. I can obtain core samples as expected. Updated server and client of course

**Comment by BloodWorkXGaming** [comment] 2017-06-08 22:50
fixed in 2.57 with new version of IP

**Closed by BloodWorkXGaming** 2017-06-08 22:50 UTC
