### ISSUE TITLE
Libvulpes and Advanced Rocketry engine has the same recipe

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-1#24] opened 2017-05-20 12:27 UTC
Libvulpes and Advanced Rocketry engine has the same recipe.

**Comment by BloodWorkXGaming** [comment] 2017-05-20 12:29
Which of then work for the multi block?

TheKrister2 <notifications@github.com> schrieb am Sa., 20. Mai 2017, 14:27:

**Comment by TheKrister2** [comment] 2017-05-20 13:16
The Advanced Rocketry motor is the only one that works for it's multiblock structures.

**Comment by PotDucky** [comment] 2017-05-21 23:07
Duplicate of https://github.com/AllTheMods/ATM-1/issues/20 will be fixed in next version due in a few days.

**Closed by PotDucky** 2017-05-21 23:07 UTC
